### ISSUE TITLE
Sata Intel Series 600 Controller

### ISSUE THREAD

**Issue by hipco** [glekner/Z690I-AORUS-OC-EFI#7]
To replace the Generic SATA Controller in System Info with Series 600 Controller.

Latest CtlnaAHCIPort.kext and add in Info.plist

`		<dict>
			<key>CFBundleIdentifier</key>
			<string>com.apple.driver.CtlnaAHCIPort</string>
			<key>Chipset Name</key>
			<string>600 Series Chipset</string>
			<key>IOClass</key>
			<string>CtlnaIntelPchSeriesAHCI</string>
			<key>IONameMatch</key>
			<array>
				<string>pci8086,7ae2</string>
			</array>
			<key>IOProbeScore</key>
			<integer>900</integer>
			<key>IOProviderClass</key>
			<string>IOPCIDevice</string>
			<key>Vendor Name</key>
			<string>Intel</string>
		</dict>
	</dict>`

**Comment by glekner** [comment]
what are the benefits here besides naming?

**Comment by hipco** [comment]
Only cosmetic. Might be a problem with SATA Hotplug with this kext.
![Screenshot](https://user-images.githubusercontent.com/59048928/168279715-527b2cef-855b-4b8b-8b76-fbcc887731fb.png)

**Comment by glekner** [comment]
can you create a PR with a fix?

**Comment by hipco** [comment]
It's just a little enhancement. No need for a PR.

`			<dict>
				<key>Arch</key>
				<string>Any</string>
				<key>BundlePath</key>
				<string>CtlnaAHCIPort.kext</string>
				<key>Comment</key>
				<string></string>
				<key>Enabled</key>
				<true/>
				<key>ExecutablePath</key>
				<string>Contents/MacOS/CtlnaAHCIPort</string>
				<key>MaxKernel</key>
				<string></string>
				<key>MinKernel</key>
				<string></string>
				<key>PlistPath</key>
				<string>Contents/Info.plist</string>
			</dict>`
[CtlnaAHCIPort.kext.zip](https://github.com/glekner/GIGABYTE-Z690I-Hackintosh/files/8693758/CtlnaAHCIPort.kext.zip)
